"use client";

// import type {Metadata} from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Menu from "../components/menu";
import Grid from "@mui/material/Grid2";

// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

import {ReactNode} from "react";
import {ThemeProvider} from "@mui/material";
import theme from "@/theme/theme";
import "./globals.css";

{
    /* CssBaseline aplica o reset de estilos padrão do Material-UI */
}
{
    /* <CssBaseline /> */
}

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = ({children}: RootLayoutProps) => {
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={theme}>
                    <Menu />

                    <Grid container spacing={5} sx={{padding: 3}}>
                        {children}
                    </Grid>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="pt">
//             {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body> */}

//             <body>
// <Menu />

// <Grid container spacing={5} sx={{padding: 3}}>
//     {children}
// </Grid>
//             </body>
//         </html>
//     );
// }
